[package]
name = "grinworkers"
version = "0.1.0"
edition = "2021"
author = "cliik"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = {version = "3.2", features = ["yaml"]}
shellexpand = "2.1.0"
